# official tutorial 
# mkdocs-material: https://squidfunk.github.io/mkdocs-material/
# mkdocs: https://www.mkdocs.org/user-guide/configuration/

# Site information
site_name: Belén Cebrián | Notas públicas
site_author: Belén Cebrián
site_url: https://belencebrian.github.io/Notes/

site_description: Mis notas públicas, creadas con Obsidian y almacenadas en GitHub / My public notes, created with Obsidian and hosted on GitHub 

# Repository information
repo_url: https://github.com/BelenCebrian/Notes

# Configuration
theme:
    name: 'material'
    locale: es
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
        
    font:
      text: Roboto #Gentium Basic
      code: Roboto Mono #Fira Code

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html

# neoteori
# https://www.neoteroi.dev/mkdocs-plugins/
  - neoteroi.cards
  - neoteroi.timeline

# pymdownx
# https://facelessuser.github.io/pymdown-extensions/
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        # Mermaid diagrams
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true

  - toc:
      permalink: true

# Plugins

plugins:
  - search
  - roamlinks 
  - mermaid2
  - pdf-export
  - git-revision-date-localized
      locale: es
      type: datetime
      timezone: Europe/Madrid
      fallback_to_build_date: false
      enable_creation_date: true

# Extra

extra_css:
  - css/neoteroi-mkdocs.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
