# official tutorial 
# mkdocs-material: https://squidfunk.github.io/mkdocs-material/
# mkdocs: https://www.mkdocs.org/user-guide/configuration/

site_name: Belén Cebrián | Notas públicas
site_author: Belén Cebrián
site_description: Mis notas públicas, creadas con Obsidian y almacenadas en GitHub / My public notes, created with Obsidian and hosted on GitHub 
repo_url: https://belencebrian.github.io/Notes/

theme:
    name: 'material'
    locale: es
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.tabbed 
  - pymdownx.highlight:
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
#   - pymdownx.arithmatex
#   - pymdownx.superfences
#   - pymdownx.details
#   - pymdownx.magiclink
#   - pymdownx.tasklist:
#       custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 