name: ci
on:
  push:
    branches:
      - master
      - main
      - updateTemplate
#    paths: [ docs/**.md ] # Only trigger workflow when there are changes on docs
# https://github.com/ActionsHackathon21/build-documentations/blob/main/mkdocs.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-roamlinks-plugin
      - run: pip install mkdocs-mermaid2-plugin
      - run: pip install mkdocs-pdf-export-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: mkdocs gh-deploy --force
